// ─────────────────────────────────────────────────────────────────────────
// Cinema Siqueiros — roster data
//
// All historical cinema rosters. Each member is one crew role.
// Rows are written compactly as [role, name, rating, flags] where `flags`
// is any combination of the bonus letters:
//   p = political        (rewarded at Berlin)
//   a = avant-garde      (rewarded at Locarno)
//   h = hipster          (rewarded at Sundance)
//   s = star system      (rewarded at the Oscars)
//   u = auteur           (rewarded at Venice)
//   e = social engagement(rewarded at Cannes)
// Some rosters are intentionally INCOMPLETE (a missing role), which drives the
// in-game redraw mechanic.
// ─────────────────────────────────────────────────────────────────────────

export const ROLES = [
  "Drama Director",
  "Comedy Director",
  "Genre Director",
  "STAR Director",
  "STAR Actor",
  "Comedy Actor",
  "Drama Actor",
  "Character Actor",
  "Comedy Actress",
  "Drama Actress",
  "STAR Actress",
  "Character Actress",
  "Cinematographer",
  "Composer",
  "Screenwriter",
];

// Short labels for the six "departments" used by the scoring engine.
export const BONUS_LABELS = {
  political: "Political",
  avantgarde: "Avant-garde",
  hipster: "Hipster",
  starsystem: "Star System",
  auteur: "Auteur",
  social: "Social Engagement",
};

const BONUS_MAP = {
  p: "political",
  a: "avantgarde",
  h: "hipster",
  s: "starsystem",
  u: "auteur",
  e: "social",
};

function parseBonuses(flags = "") {
  return flags
    .toLowerCase()
    .split("")
    .map((c) => BONUS_MAP[c])
    .filter(Boolean);
}

function roster(id, name, flag, rows) {
  const members = rows.map(([role, mname, rating, flags = ""]) => ({
    role,
    name: mname,
    rating,
    bonuses: parseBonuses(flags),
  }));
  // Which mandatory roles this roster cannot fill.
  const filled = new Set(members.map((m) => m.role));
  const missing = ROLES.filter((r) => !filled.has(r));
  return { id, name, flag, members, missing };
}

export const ROSTERS = [
  roster("italy60", "Italy '60s", "🇮🇹", [
    ["Drama Director", "Luchino Visconti", 87, "p"],
    ["Comedy Director", "Dino Risi", 83],
    ["Genre Director", "Sergio Leone", 90],
    ["STAR Director", "Federico Fellini", 98, "a"],
    ["STAR Actor", "Marcello Mastroianni", 95, "s"],
    ["Comedy Actor", "Alberto Sordi", 85],
    ["Drama Actor", "Vittorio Gassman", 90],
    ["Character Actor", "Leopoldo Trieste", 80],
    ["Comedy Actress", "Virna Lisi", 85],
    ["Drama Actress", "Claudia Cardinale", 84],
    ["STAR Actress", "Sophia Loren", 96, "s"],
    ["Character Actress", "Sandra Milo", 82],
    ["Cinematographer", "Giuseppe Rotunno", 81],
    ["Composer", "Ennio Morricone", 97],
    ["Screenwriter", "Ennio Flaiano", 87, "u"],
  ]),
  roster("italy50", "Italy '50s — Neorealismo", "🇮🇹", [
    ["Drama Director", "Roberto Rossellini", 89, "p"],
    ["Comedy Director", "Steno", 82],
    ["Genre Director", "Pietro Germi", 84, "e"],
    ["STAR Director", "Vittorio De Sica", 97, "e"],
    ["STAR Actor", "Totò", 90],
    ["Comedy Actor", "Aldo Fabrizi", 85],
    ["Drama Actor", "Amedeo Nazzari", 83],
    ["Character Actor", "Paolo Stoppa", 82],
    ["Comedy Actress", "Gina Lollobrigida", 87, "s"],
    ["Drama Actress", "Silvana Mangano", 87],
    ["STAR Actress", "Anna Magnani", 92],
    ["Character Actress", "Tina Pica", 80],
    ["Cinematographer", "Aldo Graziati", 82],
    ["Composer", "Alessandro Cicognini", 81],
    ["Screenwriter", "Cesare Zavattini", 88, "u"],
  ]),
  roster("italy70", "Italy '70s", "🇮🇹", [
    ["Drama Director", "Bernardo Bertolucci", 87, "u"],
    ["Comedy Director", "Mario Monicelli", 86],
    ["Genre Director", "Marco Ferreri", 82, "a"],
    ["STAR Director", "Ettore Scola", 90, "e"],
    ["STAR Actor", "Gian Maria Volontè", 92, "p"],
    ["Comedy Actor", "Ugo Tognazzi", 86],
    ["Drama Actor", "Nino Manfredi", 85],
    ["Character Actor", "Paolo Villaggio", 83, "e"],
    ["Comedy Actress", "Mariangela Melato", 83],
    ["Drama Actress", "Stefania Sandrelli", 85],
    ["STAR Actress", "Monica Vitti", 92, "s"],
    ["Character Actress", "Laura Antonelli", 82],
    ["Cinematographer", "Vittorio Storaro", 96],
    ["Composer", "Nino Rota", 97],
    ["Screenwriter", "Tonino Guerra", 89, "u"],
  ]),
  roster("italy90", "Italy '90s", "🇮🇹", [
    ["Drama Director", "Gianni Amelio", 80, "e"],
    ["Comedy Director", "Gabriele Salvatores", 84],
    ["Genre Director", "Nanni Moretti", 83, "hp"],
    ["STAR Director", "Giuseppe Tornatore", 85, "u"],
    ["STAR Actor", "Massimo Troisi", 86],
    ["Comedy Actor", "Roberto Benigni", 81, "p"],
    ["Drama Actor", "Sergio Castellitto", 80],
    ["Character Actor", "Carlo Verdone", 84],
    ["Comedy Actress", "Margherita Buy", 83],
    ["Drama Actress", "Francesca Neri", 80],
    ["STAR Actress", "Monica Bellucci", 84, "s"],
    ["Character Actress", "Angela Finocchiaro", 80],
    ["Cinematographer", "Luca Bigazzi", 81],
    ["Composer", "Luis Bacalov", 84],
    ["Screenwriter", "Vincenzo Cerami", 80],
  ]),
  roster("usa30", "USA '30s — Golden Age", "🇺🇸", [
    ["Drama Director", "Victor Fleming", 85],
    ["Comedy Director", "Frank Capra", 88],
    ["Genre Director", "Howard Hawks", 86],
    ["STAR Director", "John Ford", 96, "a"],
    ["STAR Actor", "Humphrey Bogart", 92, "s"],
    ["Comedy Actor", "Cary Grant", 88, "s"],
    ["Drama Actor", "Clark Gable", 86, "s"],
    ["Character Actor", "James Cagney", 84],
    ["Comedy Actress", "Bette Davis", 89, "s"],
    ["Drama Actress", "Vivien Leigh", 84],
    ["STAR Actress", "Katharine Hepburn", 92, "s"],
    ["Character Actress", "Jane Darwell", 78],
    ["Cinematographer", "Gregg Toland", 88],
    ["Composer", "Max Steiner", 86],
    ["Screenwriter", "Robert Riskin", 82],
  ]),
  roster("usa50", "USA '50s", "🇺🇸", [
    ["Drama Director", "Elia Kazan", 84],
    ["Comedy Director", "Billy Wilder", 96, "u"],
    ["Genre Director", "Don Siegel", 80],
    ["STAR Director", "Alfred Hitchcock", 98],
    ["STAR Actor", "Marlon Brando", 95, "s"],
    ["Comedy Actor", "Gregory Peck", 86, "s"],
    ["Drama Actor", "James Dean", 84],
    ["Character Actor", "Lee J. Cobb", 80],
    ["Comedy Actress", "Audrey Hepburn", 89, "s"],
    ["Drama Actress", "Elizabeth Taylor", 86, "s"],
    ["STAR Actress", "Marilyn Monroe", 89, "s"],
    ["Character Actress", "Thelma Ritter", 78],
    ["Cinematographer", "Leon Shamroy", 87],
    ["Composer", "Bernard Herrmann", 83],
    ["Screenwriter", "Joseph L. Mankiewicz", 85],
  ]),
  roster("usa70", "USA '70s — New Hollywood", "🇺🇸", [
    ["Drama Director", "Martin Scorsese", 93],
    ["Comedy Director", "Robert Altman", 87, "e"],
    ["Genre Director", "Stanley Kubrick", 96, "h"],
    ["STAR Director", "Francis Ford Coppola", 97, "u"],
    ["STAR Actor", "Al Pacino", 94],
    ["Comedy Actor", "Dustin Hoffman", 87],
    ["Drama Actor", "Robert De Niro", 93, "s"],
    ["Character Actor", "John Cazale", 88],
    ["Comedy Actress", "Diane Keaton", 84],
    ["Drama Actress", "Faye Dunaway", 85, "s"],
    ["STAR Actress", "Jane Fonda", 87, "p"],
    ["Character Actress", "Sissy Spacek", 81],
    ["Cinematographer", "John Alcott", 85],
    ["Composer", "John Williams", 98],
    ["Screenwriter", "Woody Allen", 90, "u"],
  ]),
  roster("usa90", "USA '90s", "🇺🇸", [
    ["Drama Director", "James Cameron", 85],
    ["Comedy Director", "Harold Ramis", 81],
    ["Genre Director", "Quentin Tarantino", 90],
    ["STAR Director", "Steven Spielberg", 94],
    ["STAR Actor", "Tom Hanks", 92, "s"],
    ["Comedy Actor", "Robin Williams", 85],
    ["Drama Actor", "Anthony Hopkins", 87],
    ["Character Actor", "Steve Buscemi", 82],
    ["Comedy Actress", "Julia Roberts", 85, "s"],
    ["Drama Actress", "Sharon Stone", 83, "s"],
    ["STAR Actress", "Michelle Pfeiffer", 86, "s"],
    ["Character Actress", "Kathy Bates", 85],
    ["Cinematographer", "John Toll", 86],
    ["Composer", "Hans Zimmer", 95],
    ["Screenwriter", "Fratelli Coen", 88, "h"],
  ]),
  roster("usa2000", "USA 2000s", "🇺🇸", [
    ["Drama Director", "David Fincher", 85],
    ["Comedy Director", "Wes Anderson", 85, "h"],
    ["Genre Director", "Christopher Nolan", 85],
    ["STAR Director", "Paul Thomas Anderson", 87],
    ["STAR Actor", "Leonardo Di Caprio", 92, "s"],
    ["Comedy Actor", "Johnny Depp", 87, "s"],
    ["Drama Actor", "Denzel Washington", 88],
    ["Character Actor", "Philip Seymour Hoffman", 86],
    ["Comedy Actress", "Cameron Diaz", 83],
    ["Drama Actress", "Charlize Theron", 87],
    ["STAR Actress", "Angelina Jolie", 88, "s"],
    ["Character Actress", "Margo Martindale", 77],
    ["Cinematographer", "Roger Deakins", 97],
    ["Composer", "Howard Shore", 84],
    ["Screenwriter", "Charlie Kaufman", 85, "a"],
  ]),
  roster("japan60", "Japan '60s", "🇯🇵", [
    ["Drama Director", "Masaki Kobayashi", 91, "u"],
    ["Comedy Director", "Yasujiro Ozu", 90, "a"],
    ["Genre Director", "Hiroshi Teshigahara", 84],
    ["STAR Director", "Akira Kurosawa", 98],
    ["STAR Actor", "Toshirō Mifune", 95, "s"],
    ["Comedy Actor", "Takashi Shimura", 85],
    ["Drama Actor", "Tatsuya Nakadai", 92, "e"],
    ["Character Actor", "Shinobu Hashimoto", 81],
    ["Comedy Actress", "Setsuko Hara", 85],
    ["Drama Actress", "Machiko Kyō", 88],
    ["STAR Actress", "Kinuyo Tanaka", 90],
    ["Character Actress", "Kyōko Kishida", 83],
    ["Cinematographer", "Kazuo Miyagawa", 83],
    ["Composer", "Masaru Satō", 83],
    ["Screenwriter", "Shinobu Hashimoto", 84],
  ]),
  roster("japan2000", "Japan 2000s", "🇯🇵", [
    ["Drama Director", "Kiyoshi Kurosawa", 86, "h"],
    ["Comedy Director", "Hayao Miyazaki", 89, "u"],
    ["Genre Director", "Takashi Miike", 83],
    ["STAR Director", "Hirokazu Kore-eda", 89, "e"],
    ["STAR Actor", "Ken Watanabe", 86, "s"],
    ["Comedy Actor", "Naoki Tanaka", 79],
    ["Drama Actor", "Hidetoshi Nishijima", 83],
    ["Character Actor", "Takeshi Kitano", 83],
    ["Comedy Actress", "Eri Fukatsu", 81],
    ["Drama Actress", "Kyōko Koizumi", 84],
    ["STAR Actress", "Rie Miyazawa", 86],
    ["Character Actress", "Miki Nakatani", 83],
    ["Cinematographer", "Hideo Yamamoto", 85],
    ["Composer", "Joe Hisaishi", 85],
    ["Screenwriter", "Sion Sono", 84],
  ]),
  roster("korea2000", "South Korea 2000s", "🇰🇷", [
    ["Drama Director", "Kim Ki-duk", 87, "a"],
    ["Comedy Director", "Lee Hae-jun", 84, "e"],
    ["Genre Director", "Park Chan-wook", 89, "h"],
    ["STAR Director", "Bong Joon-ho", 91],
    ["STAR Actor", "Song Kang-ho", 88],
    ["Comedy Actor", "Cha Tae-hyun", 82],
    ["Drama Actor", "Choi Min-sik", 86],
    ["Character Actor", "Yoo Ji-tae", 81],
    ["Comedy Actress", "Jeon Ji-hyun", 83],
    ["Drama Actress", "Lee Young-ae", 84],
    ["STAR Actress", "Jeon Do-yeon", 87],
    ["Character Actress", "Bae Doona", 83],
    ["Cinematographer", "Hong Kyung-pyo", 84],
    ["Composer", "Jo Yeong-wook", 80],
    ["Screenwriter", "Lee Chang-dong", 87, "u"],
  ]),
  roster("hongkong90", "Hong Kong '90s", "🇭🇰", [
    ["Drama Director", "Fruit Chan", 82],
    ["Comedy Director", "Peter Ho-Sun Chan", 83],
    ["Genre Director", "John Woo", 81],
    ["STAR Director", "Kar-Wai Wong", 93, "ha"],
    ["STAR Actor", "Jackie Chan", 89],
    ["Comedy Actor", "Chow Yun-fat", 87],
    ["Drama Actor", "Tony Leung", 93, "s"],
    ["Character Actor", "Leslie Cheung", 85],
    ["Comedy Actress", "Carina Lau", 83],
    ["Drama Actress", "Faye Wong", 87],
    ["STAR Actress", "Maggie Cheung", 90],
    ["Character Actress", "Charlie Yeung", 84],
    ["Cinematographer", "Christopher Doyle", 87],
    ["Composer", "Shigeru Umebayashi", 85],
    ["Screenwriter", "Jacob Cheung", 80],
  ]),
  roster("taiwan90", "Taiwan '90s", "🇹🇼", [
    ["Drama Director", "Hsiao-Hsien Hou", 85, "p"],
    ["Comedy Director", "Ang Lee", 87],
    ["Genre Director", "Tsai Ming-liang", 86, "a"],
    ["STAR Director", "Edward Yang", 91, "e"],
    ["STAR Actor", "Chang Chen", 86],
    ["Comedy Actor", "Issei Ogata", 79],
    ["Drama Actor", "Takeshi Kaneshiro", 82],
    ["Character Actor", "Sihung Lung", 84],
    ["Comedy Actress", "Shu Qi", 83],
    ["Drama Actress", "Yang Kuei-mei", 84],
    ["STAR Actress", "Chien-Lien Wu", 85],
    ["Character Actress", "Tsai Chin", 80],
    ["Cinematographer", "Wei-Han Yang", 82],
    ["Composer", "Lim Giong", 83],
    ["Screenwriter", "Chu T'ien-wen", 84],
  ]),
  roster("iran", "Iran '90s–2000s", "🇮🇷", [
    ["Drama Director", "Asghar Farhadi", 88, "e"],
    ["Comedy Director", "Jafar Panahi", 87, "p"],
    ["Genre Director", "Bahman Ghobadi", 85, "e"],
    ["STAR Director", "Abbas Kiarostami", 93, "a"],
    ["STAR Actor", "Payman Maadi", 88, "p"],
    ["Comedy Actor", "Parviz Parastui", 84, "p"],
    ["Drama Actor", "Homayoun Ershadi", 86, "p"],
    ["Character Actor", "Babak Karimi", 82, "p"],
    ["Comedy Actress", "Golshifteh Farahani", 86, "p"],
    ["Drama Actress", "Taraneh Alidoosti", 85, "p"],
    ["STAR Actress", "Leila Hatami", 88, "p"],
    ["Character Actress", "Aida Mohammadkhani", 80, "p"],
    ["Cinematographer", "Mahmoud Kalari", 79],
    ["Composer", "Peyman Yazdanian", 81],
    ["Screenwriter", "Majid Majidi", 84, "e"],
  ]),
  roster("france60", "France '60s — Nouvelle Vague", "🇫🇷", [
    ["Drama Director", "Jean-Luc Godard", 92, "a"],
    ["Comedy Director", "Georges Lautner", 83],
    ["Genre Director", "Jean-Pierre Melville", 85],
    ["STAR Director", "François Truffaut", 92, "u"],
    ["STAR Actor", "Alain Delon", 90, "s"],
    ["Comedy Actor", "Jean-Pierre Léaud", 84],
    ["Drama Actor", "Jean-Paul Belmondo", 89, "s"],
    ["Character Actor", "Michel Piccoli", 85],
    ["Comedy Actress", "Catherine Deneuve", 90, "s"],
    ["Drama Actress", "Anna Karina", 91],
    ["STAR Actress", "Brigitte Bardot", 93, "s"],
    ["Character Actress", "Bernadette Lafont", 83],
    ["Cinematographer", "Raoul Coutard", 82],
    ["Composer", "Michel Legrand", 84],
    ["Screenwriter", "Éric Rohmer", 87, "h"],
  ]),
  roster("soviet", "Soviet Union", "🟥", [
    ["Drama Director", "Sergej M. Ėjzenštejn", 91, "a"],
    ["Comedy Director", "Nikita Michalkov", 84],
    ["Genre Director", "Dziga Vertov", 89, "a"],
    ["STAR Director", "Andrej Tarkovskij", 97, "au"],
    ["STAR Actor", "Innokentij Smoktunovskij", 86],
    ["Comedy Actor", "Evgenij Leonov", 83],
    ["Drama Actor", "Aleksey Batalov", 87],
    ["Character Actor", "Jurij Nikulin", 82],
    ["Comedy Actress", "Marija Mironova", 84],
    ["Drama Actress", "Margarita Terekhova", 87],
    ["STAR Actress", "Lyubov Orlova", 86],
    ["Character Actress", "Tatyana Samoylova", 83],
    ["Cinematographer", "Vadim Yusov", 85],
    ["Composer", "Eduard Artemyev", 82],
    ["Screenwriter", "Grigorij Čuchraj", 84, "u"],
  ]),
  roster("france90", "France '90s", "🇫🇷", [
    ["Drama Director", "Leos Carax", 85, "e"],
    ["Comedy Director", "Jean-Pierre Jeunet", 83],
    ["Genre Director", "Mathieu Kassovitz", 85, "h"],
    ["STAR Director", "Luc Besson", 86],
    ["STAR Actor", "Vincent Cassel", 89, "s"],
    ["Comedy Actor", "Jean Dujardin", 88, "s"],
    ["Drama Actor", "Gérard Depardieu", 90, "s"],
    ["Character Actor", "Dominique Pinon", 82],
    ["Comedy Actress", "Fanny Ardant", 89],
    ["Drama Actress", "Isabelle Huppert", 92],
    ["STAR Actress", "Juliette Binoche", 89],
    ["Character Actress", "Sophie Marceau", 85],
    ["Cinematographer", "Darius Khondji", 86],
    ["Composer", "Alexandre Desplat", 91],
    ["Screenwriter", "Olivier Assayas", 86, "u"],
  ]),
  roster("germany70", "Germany '70s — Neuer Deutscher Film", "🇩🇪", [
    ["Drama Director", "Wim Wenders", 90, "e"],
    ["Comedy Director", "Rainer Werner Fassbinder", 87, "h"],
    ["Genre Director", "Margarethe von Trotta", 86, "p"],
    ["STAR Director", "Werner Herzog", 90, "a"],
    ["STAR Actor", "Klaus Kinski", 93, "u"],
    ["Comedy Actor", "Bruno Ganz", 86, "a"],
    ["Drama Actor", "Rüdiger Vogler", 85],
    ["Character Actor", "Mario Adorf", 81],
    ["Comedy Actress", "Senta Berger", 80],
    ["Drama Actress", "Nastassja Kinski", 85],
    ["STAR Actress", "Hanna Schygulla", 87],
    ["Character Actress", "Margit Carstensen", 85],
    ["Cinematographer", "Michael Ballhaus", 82],
    ["Composer", "Klaus Doldinger", 82],
    ["Screenwriter", "Peter Handke", 86, "u"],
  ]),
  roster("germany20", "Germany '20s/'30s", "🇩🇪", [
    ["Drama Director", "Robert Wiene", 88, "a"],
    ["Comedy Director", "Ernst Lubitsch", 87],
    ["Genre Director", "F.W. Murnau", 89, "a"],
    ["STAR Director", "Fritz Lang", 95, "u"],
    ["STAR Actor", "Emil Jannings", 87],
    ["Comedy Actor", "Reinhold Schünzel", 85],
    ["Drama Actor", "Conrad Veidt", 86],
    ["Character Actor", "Werner Krauss", 83],
    ["Comedy Actress", "Jenny Jugo", 83],
    ["Drama Actress", "Brigitte Helm", 88],
    ["STAR Actress", "Marlene Dietrich", 92, "s"],
    ["Character Actress", "Camilla Horn", 82],
    ["Cinematographer", "Karl Freund", 88],
    ["Composer", "Friedrich Hollaender", 87],
    ["Screenwriter", "Thea von Harbou", 86],
  ]),
  roster("trash", "Trash", "🗑️", [
    ["Drama Director", "Claudio Fragasso", 58],
    ["Comedy Director", "Tommy Wiseau", 55, "a"],
    ["Genre Director", "Uwe Boll", 57],
    ["STAR Director", "Ed Wood", 60, "a"],
    ["STAR Actor", "David Hasselhoff", 73],
    ["Comedy Actor", "Rob Schneider", 71],
    ["Drama Actor", "Steven Seagal", 70],
    ["Character Actor", "Kevin Sorbo", 68],
    ["Comedy Actress", "Tara Reid", 68],
    ["Drama Actress", "Denise Richards", 66],
    ["STAR Actress", "Paris Hilton", 54],
    ["Character Actress", "Juliette Danielle", 56],
    ["Cinematographer", "William C. Thompson", 60],
    ["Composer", "Richard Band", 66],
    ["Screenwriter", "Neil Breen", 59],
  ]),
  roster("argentina80", "Argentina '80s", "🇦🇷", [
    ["Drama Director", "Adolfo Aristarain", 85, "e"],
    ["Comedy Director", "Alejandro Doria", 82],
    ["Genre Director", "Héctor Olivera", 83, "p"],
    ["STAR Director", "Luis Puenzo", 86, "p"],
    ["STAR Actor", "Héctor Alterio", 86],
    ["Comedy Actor", "Alberto Olmedo", 82],
    ["Drama Actor", "Federico Luppi", 85, "u"],
    ["Character Actor", "Norman Briski", 82],
    ["Comedy Actress", "Moria Casán", 79],
    ["Drama Actress", "Graciela Borges", 85],
    ["STAR Actress", "Norma Aleandro", 88],
    ["Character Actress", "Aída Luz", 84],
    ["Cinematographer", "Ricardo Aronovich", 85],
    ["Composer", "Astor Piazzolla", 90],
    ["Screenwriter", "Aída Bortnik", 88, "p"],
  ]),
  roster("mexico2000", "Mexico 2000s", "🇲🇽", [
    ["Drama Director", "Alfonso Cuarón", 87, "u"],
    ["Comedy Director", "Luis Estrada", 84],
    ["Genre Director", "Guillermo del Toro", 85, "h"],
    ["STAR Director", "Alejandro González Iñárritu", 89],
    ["STAR Actor", "Gael García Bernal", 89],
    ["Comedy Actor", "Diego Luna", 85, "s"],
    ["Drama Actor", "Demián Bichir", 84],
    ["Character Actor", "Joaquín Cosío", 79],
    ["Comedy Actress", "Martha Higareda", 78],
    ["Drama Actress", "Vanessa Bauche", 83],
    ["STAR Actress", "Salma Hayek", 89],
    ["Character Actress", "Adriana Barraza", 85],
    ["Cinematographer", "Emmanuel Lubezki", 90],
    ["Composer", "Alejandro Giacoman", 82],
    ["Screenwriter", "Guillermo Arriaga", 85, "u"],
  ]),
  roster("spain2000", "Spain 2000s", "🇪🇸", [
    ["Drama Director", "Alejandro Amenábar", 87, "p"],
    ["Comedy Director", "Emilio Martínez-Lázaro", 80],
    ["Genre Director", "Álex de la Iglesia", 84],
    ["STAR Director", "Pedro Almodóvar", 88, "h"],
    ["STAR Actor", "Antonio Banderas", 89, "s"],
    ["Comedy Actor", "Santiago Segura", 83],
    ["Drama Actor", "Javier Bardem", 90, "s"],
    ["Character Actor", "Javier Cámara", 86],
    ["Comedy Actress", "Carmen Maura", 85],
    ["Drama Actress", "Maribel Verdú", 86],
    ["STAR Actress", "Penélope Cruz", 88, "s"],
    ["Character Actress", "Rossy de Palma", 85, "h"],
    ["Cinematographer", "José Luis Alcaine", 86],
    ["Composer", "Alberto Iglesias", 87],
    ["Screenwriter", "Jorge Guerricaechevarría", 86],
  ]),
  roster("romania", "Romania — Romanian New Wave", "🇷🇴", [
    ["Drama Director", "Cristi Puiu", 85, "e"],
    ["Comedy Director", "Nae Caranfil", 82],
    ["Genre Director", "Radu Jude", 84, "ha"],
    ["STAR Director", "Cristian Mungiu", 86, "eu"],
    ["STAR Actor", "Vlad Ivanov", 85],
    ["Comedy Actor", "Mircea Diaconu", 82],
    ["Drama Actor", "Ioan Fiscuteanu", 83],
    ["Character Actor", "Doru Ana", 78],
    ["Comedy Actress", "Ioana Flora", 79],
    ["Drama Actress", "Laura Vasiliu", 81],
    ["STAR Actress", "Anamaria Marinca", 87],
    ["Character Actress", "Tamara Buciuceanu", 80],
    ["Cinematographer", "Oleg Mutu", 83],
    ["Composer", "Alexander Bălănescu", 83],
    ["Screenwriter", "Corneliu Porumboiu", 81, "u"],
  ]),
  roster("poland80", "Poland '80s", "🇵🇱", [
    ["Drama Director", "Andrzej Wajda", 89, "up"],
    ["Comedy Director", "Agnieszka Holland", 86],
    ["Genre Director", "Krzysztof Zanussi", 86, "u"],
    ["STAR Director", "Krzysztof Kieślowski", 94, "u"],
    ["STAR Actor", "Daniel Olbrychski", 87],
    ["Comedy Actor", "Stanisław Tym", 83],
    ["Drama Actor", "Jerzy Stuhr", 86],
    ["Character Actor", "Janusz Gajos", 84],
    ["Comedy Actress", "Katarzyna Figura", 82],
    ["Drama Actress", "Grażyna Szapołowska", 81],
    ["STAR Actress", "Krystyna Janda", 87],
    ["Character Actress", "Danuta Szaflarska", 81],
    ["Cinematographer", "Sławomir Idziak", 85],
    ["Composer", "Wojciech Kilar", 84],
    ["Screenwriter", "Krzysztof Piesiewicz", 87, "u"],
  ]),
  roster("russia2010", "Russia 2010s", "🇷🇺", [
    ["Drama Director", "Kantemir Balagov", 82, "e"],
    ["Comedy Director", "Kirill Serebrennikov", 83],
    ["Genre Director", "Aleksandr Sokurov", 86, "a"],
    ["STAR Director", "Andrey Zvyagintsev", 87, "e"],
    ["STAR Actor", "Konstantin Khabensky", 85],
    ["Comedy Actor", "Sergey Burunov", 77],
    ["Drama Actor", "Aleksey Serebryakov", 83],
    ["Character Actor", "Roman Madyanov", 80],
    ["Comedy Actress", "Svetlana Khodchenkova", 82],
    ["Drama Actress", "Mar'jana Spivak", 81],
    ["STAR Actress", "Elena Lyadova", 84],
    ["Character Actress", "Yuliya Aug", 82],
    ["Cinematographer", "Mikhail Krichman", 83],
    ["Composer", "Eduard Artemyev", 86],
    ["Screenwriter", "Oleg Negin", 82],
  ]),
  roster("france30", "France '30s — Réalisme poétique", "🇫🇷", [
    ["Drama Director", "Marcel Carné", 89, "u"],
    ["Comedy Director", "René Clair", 86],
    ["Genre Director", "Jean Vigo", 87],
    ["STAR Director", "Jean Renoir", 94, "u"],
    ["STAR Actor", "Jean Gabin", 88, "s"],
    ["Comedy Actor", "Raimu", 84],
    ["Drama Actor", "Pierre Fresnay", 83],
    ["Character Actor", "Louis Jouvet", 83],
    ["Comedy Actress", "Danielle Darrieux", 85],
    ["Drama Actress", "Michèle Morgan", 88],
    ["STAR Actress", "Arletty", 89, "s"],
    ["Character Actress", "Françoise Rosay", 83],
    ["Cinematographer", "Christian Matras", 86],
    ["Composer", "Maurice Jaubert", 87],
    ["Screenwriter", "Jacques Prévert", 89, "u"],
  ]),
  roster("france50", "France '50s", "🇫🇷", [
    ["Drama Director", "Alain Resnais", 89, "ae"],
    ["Comedy Director", "Jacques Tati", 86, "h"],
    ["Genre Director", "Henri-Georges Clouzot", 87],
    ["STAR Director", "Robert Bresson", 92, "p"],
    ["STAR Actor", "Yves Montand", 86, "s"],
    ["Comedy Actor", "Fernandel", 85],
    ["Drama Actor", "Gérard Philipe", 86],
    ["Character Actor", "Michel Simon", 84],
    ["Comedy Actress", "Martine Carol", 84],
    ["Drama Actress", "Simone Signoret", 89],
    ["STAR Actress", "Jeanne Moreau", 88],
    ["Character Actress", "Pauline Carton", 82],
    ["Cinematographer", "Henri Alekan", 86],
    ["Composer", "Georges Auric", 83],
    ["Screenwriter", "Jean Aurenche", 84],
  ]),
  roster("fratpack", "Frat Pack", "🇺🇸", [
    // No Drama Director / Drama Actor / Drama Actress — an incomplete roster.
    ["Comedy Director", "Todd Phillips", 83, "s"],
    ["Genre Director", "Judd Apatow", 77, "h"],
    ["STAR Director", "Adam McKay", 80],
    ["STAR Actor", "Ben Stiller", 79, "s"],
    ["Comedy Actor", "Owen Wilson", 76],
    ["Character Actor", "Will Ferrell", 78, "a"],
    ["Comedy Actress", "Christine Taylor", 74],
    ["STAR Actress", "Kathryn Hahn", 76],
    ["Character Actress", "Leslie Mann", 75],
    ["Cinematographer", "Oliver Wood", 77],
    ["Composer", "Theodore Shapiro", 80],
    ["Screenwriter", "John Hamburg", 80],
  ]),
  roster("brazil60", "Brazil '60s — Cinema Novo", "🇧🇷", [
    ["Drama Director", "Nelson Pereira dos Santos", 84, "ae"],
    ["Comedy Director", "Carlos Manga", 78],
    ["Genre Director", "Walter Hugo Khouri", 81, "ae"],
    ["STAR Director", "Glauber Rocha", 88, "a"],
    ["STAR Actor", "Othon Bastos", 86],
    ["Comedy Actor", "Grande Otelo", 86, "h"],
    ["Drama Actor", "Geraldo Del Rey", 83],
    ["Character Actor", "Hugo Carvana", 82],
    ["Comedy Actress", "Norma Bengell", 83],
    ["Drama Actress", "Fernanda Montenegro", 87, "u"],
    ["STAR Actress", "Odete Lara", 85],
    ["Character Actress", "Helena Ignez", 84],
    ["Cinematographer", "Affonso Beato", 81],
    ["Composer", "Antônio Carlos Jobim", 87],
    ["Screenwriter", "Joaquim Pedro de Andrade", 82],
  ]),
  roster("cinepanettone", "Cinepanettone", "🍰", [
    // No Drama Director / Drama Actor / Drama Actress — an incomplete roster.
    ["Comedy Director", "Neri Parenti", 65],
    ["Genre Director", "Enrico Oldoini", 67, "h"],
    ["STAR Director", "Carlo Vanzina", 71, "a"],
    ["STAR Actor", "Christian De Sica", 76, "a"],
    ["Comedy Actor", "Massimo Boldi", 69, "a"],
    ["Character Actor", "Dogui", 66, "a"],
    ["Comedy Actress", "Anna Falchi", 64, "a"],
    ["STAR Actress", "Sabrina Ferilli", 70],
    ["Character Actress", "Anna Maria Barbera", 60, "h"],
    ["Cinematographer", "Gianlorenzo Battaglia", 63],
    ["Composer", "Manuel De Sica", 77],
    ["Screenwriter", "Fratelli Vanzina", 62],
  ]),
  roster("senegal70", "Senegal '70s", "🇸🇳", [
    ["Drama Director", "Djibril Diop Mambéty", 84, "a"],
    ["Comedy Director", "Momar Thiam", 77, "p"],
    ["Genre Director", "Safi Faye", 80, "h"],
    ["STAR Director", "Ousmane Sembène", 85, "e"],
    ["STAR Actor", "Makhouredia Gueye", 84, "h"],
    ["Comedy Actor", "Magaye Niang", 76],
    ["Drama Actor", "Thierno Leye", 78, "p"],
    ["Character Actor", "Douta Seck", 77],
    ["Comedy Actress", "Seune Samb", 78],
    ["Drama Actress", "Tabata Ndiaye", 79, "e"],
    ["STAR Actress", "Mareme Niang", 80],
    ["Character Actress", "Aminata Fall", 76],
    ["Cinematographer", "Pap Samba Sow", 80],
    ["Composer", "Samba Diabara Samb", 75],
    ["Screenwriter", "Ben Diogaye Bèye", 73],
  ]),
  roster("greece2010", "Greece 2010s — Weird Wave", "🇬🇷", [
    ["Drama Director", "Pantelis Voulgaris", 84, "h"],
    ["Comedy Director", "Nikos Zapatinas", 79],
    ["Genre Director", "Yorgos Lanthimos", 88, "h"],
    ["STAR Director", "Theo Angelopoulos", 90, "u"],
    ["STAR Actor", "Alexis Georgoulis", 80],
    ["Comedy Actor", "Thodoris Atheridis", 77],
    ["Drama Actor", "Vangelis Mourikis", 79],
    ["Character Actor", "Antonis Kafetzopoulos", 83],
    ["Comedy Actress", "Zeta Makrypoulia", 79],
    ["Drama Actress", "Katerina Didaskalou", 83],
    ["STAR Actress", "Angeliki Papoulia", 84],
    ["Character Actress", "Maria Tzompanaki", 78],
    ["Cinematographer", "Thimios Bakatakis", 84],
    ["Composer", "Evanthia Reboutsika", 80],
    ["Screenwriter", "Efthymis Filippou", 84],
  ]),
  roster("india", "India — Parallel Cinema", "🇮🇳", [
    ["Drama Director", "Mrinal Sen", 85, "a"],
    ["Comedy Director", "Sai Paranjpye", 84],
    ["Genre Director", "Ritwik Ghatak", 84],
    ["STAR Director", "Satyajit Ray", 90, "e"],
    ["STAR Actor", "Rajesh Khanna", 85],
    ["Comedy Actor", "Utpal Dutt", 86],
    ["Drama Actor", "Naseeruddin Shah", 85],
    ["Character Actor", "Sivaji Ganesan", 83],
    ["Comedy Actress", "Madhubala", 85],
    ["Drama Actress", "Smita Patil", 87],
    ["STAR Actress", "Savitri", 88],
    ["Character Actress", "Shabana Azmi", 81],
    ["Cinematographer", "Subrata Mitra", 84],
    ["Composer", "Vanraj Bhatia", 82],
    ["Screenwriter", "Vijay Tendulkar", 84, "e"],
  ]),
  roster("china", "China — The Sixth Generation", "🇨🇳", [
    ["Drama Director", "Jia Zhangke", 84, "p"],
    ["Comedy Director", "Feng Xiaogang", 83],
    ["Genre Director", "Chen Kaige", 87],
    ["STAR Director", "Zhang Yimou", 89, "p"],
    ["STAR Actor", "Jiang Wen", 85],
    ["Comedy Actor", "Fan Wei", 80],
    ["Drama Actor", "Ge You", 84, "p"],
    ["Character Actor", "Wang Xueqi", 81],
    ["Comedy Actress", "Xu Fan", 79],
    ["Drama Actress", "Zhou Xun", 83, "p"],
    ["STAR Actress", "Gong Li", 90],
    ["Character Actress", "Joan Chen", 85],
    ["Cinematographer", "Lü Yue", 86],
    ["Composer", "Zhao Jiping", 84],
    ["Screenwriter", "Liu Heng", 80],
  ]),
  roster("scandinavia", "Scandinavia — Hall of Fame", "❄️", [
    ["Drama Director", "Carl Theodor Dreyer", 94, "u"],
    ["Comedy Director", "Aki Kaurismäki", 86, "h"],
    ["Genre Director", "Victor Sjöström", 84, "a"],
    ["STAR Director", "Ingmar Bergman", 98, "u"],
    ["STAR Actor", "Max von Sydow", 94, "s"],
    ["Comedy Actor", "Robert Gustafsson", 83],
    ["Drama Actor", "Erland Josephson", 90],
    ["Character Actor", "Victor Sjöström", 87],
    ["Comedy Actress", "Bibi Andersson", 93],
    ["Drama Actress", "Liv Ullmann", 96, "e"],
    ["STAR Actress", "Ingrid Bergman", 90, "s"],
    ["Character Actress", "Noomi Rapace", 85],
    ["Cinematographer", "Sven Nykvist", 97],
    ["Composer", "Jóhann Jóhannsson", 87],
    ["Screenwriter", "Joachim Trier", 84, "h"],
  ]),
  roster("dogma95", "Dogma 95", "🎬", [
    // Highly incomplete — no Comedy/Genre directors, comedy performers or composer.
    ["Drama Director", "Thomas Vinterberg", 87, "u"],
    ["STAR Director", "Lars Von Trier", 88, "u"],
    ["STAR Actor", "Mads Mikkelsen", 87],
    ["Drama Actor", "Stellan Skarsgård", 87, "s"],
    ["Character Actor", "Jens Albinus", 85],
    ["Drama Actress", "Trine Dyrholm", 86],
    ["STAR Actress", "Björk", 86, "h"],
    ["Character Actress", "Paprika Steen", 83],
    ["Cinematographer", "Anthony Dod Mantle", 87],
    ["Screenwriter", "Mogens Rukov", 81],
  ]),
  roster("uk60", "UK '60s", "🇬🇧", [
    ["Drama Director", "John Schlesinger", 86, "e"],
    ["Comedy Director", "Tony Richardson", 82],
    ["Genre Director", "Terence Fisher", 80],
    ["STAR Director", "David Lean", 89, "s"],
    ["STAR Actor", "Laurence Olivier", 93, "u"],
    ["Comedy Actor", "Peter Sellers", 90, "s"],
    ["Drama Actor", "Peter O'Toole", 93],
    ["Character Actor", "Roy Kinnear", 79],
    ["Comedy Actress", "Susannah York", 83],
    ["Drama Actress", "Vanessa Redgrave", 87, "s"],
    ["STAR Actress", "Julie Christie", 90],
    ["Character Actress", "Margaret Rutherford", 84],
    ["Cinematographer", "Freddie Young", 93],
    ["Composer", "Maurice Jarre", 85],
    ["Screenwriter", "Harold Pinter", 88, "u"],
  ]),
  // Mumblecore — the indie hipster movement. Missing a Genre Director, so it is
  // an intentionally incomplete roster. Its members carry the hipster bonus,
  // which makes any crew built from them a Sundance powerhouse.
  roster("mumblecore", "Mumblecore", "🎥", [
    ["Drama Director", "Alex Ross Perry", 76, "h"],
    ["Comedy Director", "Joe Swanberg", 77, "h"],
    ["STAR Director", "Andrew Bujalski", 75],
    ["STAR Actor", "Mark Duplass", 80, "h"],
    ["Comedy Actor", "Jake Johnson", 78, "h"],
    ["Drama Actor", "Jay Duplass", 77, "h"],
    ["Character Actor", "Kent Osborne", 76],
    ["Comedy Actress", "Amy Seimetz", 81, "h"],
    ["Drama Actress", "Kate Lyn Sheil", 80, "h"],
    ["STAR Actress", "Greta Gerwig", 84, "h"],
    ["Character Actress", "Lena Dunham", 79],
    ["Cinematographer", "Sean Price Williams", 76],
    ["Composer", "Kevin Bewersdorf", 72],
    ["Screenwriter", "Duplass Brothers", 78, "h"],
  ]),
  // SNL Universe — a comedy ensemble missing the three drama roles, so it is an
  // intentionally incomplete roster (like the Frat Pack).
  roster("snl", "SNL Universe — First Generation", "📺", [
    ["Comedy Director", "John Landis", 83],
    ["Genre Director", "Ivan Reitman", 84],
    ["STAR Director", "Harold Ramis", 84],
    ["STAR Actor", "Bill Murray", 86, "s"],
    ["Comedy Actor", "Chevy Chase", 83, "s"],
    ["Character Actor", "John Belushi", 82, "a"],
    ["Comedy Actress", "Jane Curtin", 77],
    ["STAR Actress", "Gilda Radner", 80],
    ["Character Actress", "Laraine Newman", 76],
    ["Cinematographer", "Stephen M. Katz", 74],
    ["Composer", "Elmer Bernstein", 86],
    ["Screenwriter", "Dan Aykroyd", 79],
  ]),
  roster("nz2000", "New Zealand 2000s", "🇳🇿", [
    ["Drama Director", "Jane Campion", 85, "e"],
    ["Comedy Director", "Taika Waititi", 83, "h"],
    ["Genre Director", "Andrew Niccol", 82],
    ["STAR Director", "Peter Jackson", 88],
    ["STAR Actor", "Russell Crowe", 87, "s"],
    ["Comedy Actor", "Jemaine Clement", 83, "h"],
    ["Drama Actor", "Sam Neill", 85],
    ["Character Actor", "Temuera Morrison", 74],
    ["Comedy Actress", "Melanie Lynskey", 77],
    ["Drama Actress", "Kerry Fox", 83],
    ["STAR Actress", "Anna Paquin", 86],
    ["Character Actress", "Lucy Lawless", 79],
    ["Cinematographer", "Stuart Dryburgh", 84],
    ["Composer", "Hanan Townshend", 78],
    ["Screenwriter", "Fran Walsh", 86],
  ]),
  roster("australia90", "Australia '90s", "🇦🇺", [
    ["Drama Director", "Peter Weir", 85, "u"],
    ["Comedy Director", "Stephan Elliott", 84],
    ["Genre Director", "George Miller", 86],
    ["STAR Director", "Baz Luhrmann", 86, "s"],
    ["STAR Actor", "Mel Gibson", 87, "s"],
    ["Comedy Actor", "Paul Hogan", 83],
    ["Drama Actor", "Geoffrey Rush", 88, "u"],
    ["Character Actor", "Bill Hunter", 80],
    ["Comedy Actress", "Toni Collette", 84],
    ["Drama Actress", "Cate Blanchett", 92, "s"],
    ["STAR Actress", "Nicole Kidman", 89, "s"],
    ["Character Actress", "Rachel Griffiths", 84],
    ["Cinematographer", "Andrew Lesnie", 89],
    ["Composer", "David Hirschfelder", 84],
    ["Screenwriter", "Jan Sardi", 83],
  ]),
  // ── NEW ROSTERS — paste these inside the ROSTERS array in data.js ──────────

roster("silentHollywood", "Hollywood Silent Era", "🎞️", [
  ["Drama Director",     "D. W. Griffith",      86, "a"],
  ["Comedy Director",    "Buster Keaton",        87],
  ["Genre Director",     "Tod Browning",         86],
  ["STAR Director",      "Cecil B. DeMille",     87],
  ["STAR Actor",         "Charlie Chaplin",      94, "u"],
  ["Comedy Actor",       "Harold Lloyd",         85, "h"],
  ["Drama Actor",        "Rodolfo Valentino",    86, "s"],
  ["Character Actor",    "Douglas Fairbanks",    85, "s"],
  ["Comedy Actress",     "Mabel Normand",        83],
  ["Drama Actress",      "Greta Garbo",          87, "s"],
  ["STAR Actress",       "Gloria Swanson",       89, "s"],
  ["Character Actress",  "Louise Dresser",       84],
  ["Cinematographer",    "Karl Struss",          85],
  // Composer intentionally missing — drives the redraw mechanic
  ["Screenwriter",       "Anita Loos",           85],
]),

roster("hungary70", "Hungary '70s", "🇭🇺", [
  ["Drama Director",     "István Szabó",         84, "p"],
  ["Comedy Director",    "Péter Bacsó",          84],
  ["Genre Director",     "Márta Mészáros",       84, "p"],
  ["STAR Director",      "Zoltán Fábri",         87, "u"],
  ["STAR Actor",         "Zoltán Latinovits",    85],
  ["Comedy Actor",       "Alfonzó",              84],
  ["Drama Actor",        "Antal Páger",          83],
  ["Character Actor",    "József Bihari",        79],
  ["Comedy Actress",     "Anikó Sáfár",          81],
  ["Drama Actress",      "Anna Nagy",            82],
  ["STAR Actress",       "Mari Törőcsik",        84],
  ["Character Actress",  "Margit Dajka",         82],
  ["Cinematographer",    "János Kende",          80],
  ["Composer",           "Péter Eötvös",         83],
  ["Screenwriter",       "Miklós Jancsó",        85, "e"],
]),

roster("czechoslovakia60", "Czechoslovakia '60s", "🇨🇿", [
  ["Drama Director",     "Jan Němec",            84, "p"],
  ["Comedy Director",    "Jiří Menzel",          86],
  ["Genre Director",     "Věra Chytilová",       85, "a"],
  ["STAR Director",      "Miloš Forman",         90, "u"],
  ["STAR Actor",         "Vlastimil Brodský",    86],
  ["Comedy Actor",       "Jan Werich",           81],
  ["Drama Actor",        "Rudolf Hrušínský",     87],
  ["Character Actor",    "Miloš Kopecký",        83],
  ["Comedy Actress",     "Iva Janžurová",        86],
  ["Drama Actress",      "Emília Vášáryová",     83],
  ["STAR Actress",       "Jana Brejchová",       85],
  ["Character Actress",  "Olga Schoberová",      79],
  ["Cinematographer",    "Miroslav Ondříček",    84],
  ["Composer",           "Zdeněk Liška",         82],
  ["Screenwriter",       "Juraj Herz",           87, "p"],
]),

roster("belgiumHallOfFame", "Belgium Hall of Fame", "🇧🇪", [
  ["Drama Director",     "Chantal Akerman",      87, "a"],
  ["Comedy Director",    "Sam Garbarski",        82],
  ["Genre Director",     "Fabrice Du Welz",      79],
  ["STAR Director",      "Agnes Varda",          88, "u"],
  ["STAR Actor",         "Jean-Claude Van Damme", 85, "s"],
  ["Comedy Actor",       "Benoît Poelvoorde",    80],
  ["Drama Actor",        "Matthias Schoenaerts", 84],
  ["Character Actor",    "Olivier Gourmet",      84],
  ["Comedy Actress",     "Yolande Moreau",       83],
  ["Drama Actress",      "Virginie Efira",       82],
  ["STAR Actress",       "Cécile de France",     85],
  ["Character Actress",  "Barbara Sarafian",     81],
  ["Cinematographer",    "Benoît Debie",         84],
  ["Composer",           "Wim Mertens",          83],
  ["Screenwriter",       "Felix Van Groeningen", 84],
]),

// Intentionally incomplete roster — many missing roles, fits the surrealist theme
roster("surrealistCinema", "Surrealist Cinema", "🎩", [
  ["Drama Director",     "David Lynch",          90, "a"],
  ["Comedy Director",    "Alejandro Jodorowsky", 86, "a"],
  ["STAR Director",      "Luis Buñuel",          90, "a"],
  ["STAR Actor",         "Fernando Rey",         87],
  ["Drama Actor",        "Pierre Batcheff",      80],
  ["Character Actor",    "Jack Nance",           79, "a"],
  ["Drama Actress",      "Delphine Seyrig",      86],
  ["STAR Actress",       "Isabella Rossellini",  87, "u"],
  ["Character Actress",  "Giulietta Masina",     82],
  ["Cinematographer",    "Gabriel Figueroa",     86],
  ["Screenwriter",       "Salvador Dalí",        86, "ah"],
  // Missing: Genre Director, STAR Actor (duplicate role), Comedy Actor,
  // Comedy Actress, Composer — intentional gaps drive the redraw mechanic
]),
];

// ── GOAT ROSTER — never enters the draft pool, only used as the final boss ──
// Defined as a plain team map (role -> member) so it plugs directly into
// scoreBreakdown() without going through the roster() helper.
export const GOAT_TEAM = {
  "Drama Director":    { name: "Carl Theodor Dreyer",  rating: 94, bonuses: ["auteur"] },
  "Comedy Director":   { name: "Billy Wilder",          rating: 96, bonuses: ["auteur"] },
  "Genre Director":    { name: "Stanley Kubrick",       rating: 96, bonuses: ["hipster"] },
  "STAR Director":     { name: "Federico Fellini",      rating: 98, bonuses: ["avantgarde"] },
  "STAR Actor":        { name: "Toshirō Mifune",        rating: 95, bonuses: [] },
  "Comedy Actor":      { name: "Peter Sellers",         rating: 90, bonuses: ["starsystem"] },
  "Drama Actor":       { name: "Tony Leung",            rating: 93, bonuses: ["starsystem"] },
  "Character Actor":   { name: "John Cazale",           rating: 88, bonuses: [] },
  "Comedy Actress":    { name: "Bibi Andersson",        rating: 93, bonuses: [] },
  "Drama Actress":     { name: "Liv Ullmann",           rating: 96, bonuses: ["social"] },
  "STAR Actress":      { name: "Sophia Loren",          rating: 96, bonuses: ["starsystem"] },
  "Character Actress": { name: "Rossy de Palma",        rating: 85, bonuses: ["hipster"] },
  "Cinematographer":   { name: "Sven Nykvist",          rating: 97, bonuses: [] },
  "Composer":          { name: "John Williams",         rating: 98, bonuses: [] },
  "Screenwriter":      { name: "Woody Allen",           rating: 90, bonuses: [] },
};
